image: golang:alpine

variables:
  GO111MODULE: "on"

before_script:
  - apk add git

stages:
  - test

unit_test:
  stage: test
  script:
    - go test -race -v ./...

integration_test:
  stage: test
  only:
    variables:
      - $BOT_TOKEN
  script:
    - go test -tags integration -race -v ./...

