image: golang:alpine

variables:
  GO111MODULE: "on"
  CGO_ENABLED: 0

before_script:
  - apk add git

stages:
  - test

unit_test:
  stage: test
  script:
    - go test ./...

integration_test:
  stage: test
  only:
    variables:
      - BOT_TOKEN
  script:
    - go test -tags integration ./...

