image: golang:alpine

variables:
  GO111MODULE: "on"
  CGO_ENABLED: 0

before_script:
  - apk add git

stages:
  - test

unit_test:
  stage: test
  script:
    - go test -tags unit -v ./...

integration_test:
  stage: test
  only:
    variables:
      - $BOT_TOKEN
  script:
    # Timeout test after 120 seconds (2 minutes)
    - timeout 120 go test -tags integration -v ./...

